name: portfolio_divya_pawar
description: Divya Pawar - Flutter Developer Portfolio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.0.20
  scrollable_positioned_list: ^0.3.8
  google_fonts: ^3.0.1
  path_provider: ^2.0.11
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  google_sign_in: ^6.0.2
  cloud_firestore: ^4.3.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/resume/
